"""add user_id and liscense number to rider

Revision ID: 896b9838acd5
Revises: d45c1f4431df
Create Date: 2025-08-05 21:30:57.858897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896b9838acd5'
down_revision = 'd45c1f4431df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('rider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('license_number', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_rider_user', 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rider', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rider_user', type_='foreignkey')
        batch_op.drop_column('license_number')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
