"""Initial Schema

Revision ID: eb6edbd8dab9
Revises: 
Create Date: 2025-06-19 17:29:23.177248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6edbd8dab9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resturant',
    sa.Column('resturant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('logo_url', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('open_hours', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('resturant_id')
    )
    op.create_table('rider',
    sa.Column('rider_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('vehicle_type', sa.String(length=45), nullable=False),
    sa.Column('current_location_lat', sa.Float(), nullable=False),
    sa.Column('current_location_lng', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('rider_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.Column('state', sa.String(length=45), nullable=False),
    sa.Column('zip_code', sa.String(length=45), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], onupdate='RESTRICT'),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('menu_item',
    sa.Column('menuitem_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resturant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=45), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=45), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['resturant_id'], ['resturant.resturant_id'], ),
    sa.PrimaryKeyConstraint('menuitem_id')
    )
    op.create_table('cart_details',
    sa.Column('cartdetails_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('menuitem_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_id'], ),
    sa.PrimaryKeyConstraint('cartdetails_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=True),
    sa.Column('resturant_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.ForeignKeyConstraint(['resturant_id'], ['resturant.resturant_id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['rider.rider_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('delivery_info',
    sa.Column('deliveryinfo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('delivery_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], onupdate='RESTRICT'),
    sa.ForeignKeyConstraint(['rider_id'], ['rider.rider_id'], onupdate='RESTRICT'),
    sa.PrimaryKeyConstraint('deliveryinfo_id')
    )
    op.create_table('order_details',
    sa.Column('orderdetails_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menuitem_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['menuitem_id'], ['menu_item.menuitem_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('orderdetails_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    op.drop_table('delivery_info')
    op.drop_table('order')
    op.drop_table('cart_details')
    op.drop_table('menu_item')
    op.drop_table('cart')
    op.drop_table('address')
    op.drop_table('user')
    op.drop_table('rider')
    op.drop_table('resturant')
    # ### end Alembic commands ###
